/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BetterMermaidPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  language: "en",
  customCss: "",
  enableClickToZoom: true,
  modalWidthPercent: 80,
  modalHeightPercent: 80,
  defaultZoomLevel: 100,
  enhanceReadability: true
};
var STRINGS = {
  en: {
    settingsTitle: "Better Mermaid Settings",
    languageLabel: "Language",
    languageDesc: "Display language for plugin UI",
    enableClickToZoom: "Enable click to zoom",
    enableClickToZoomDesc: "Click on a Mermaid diagram in reading mode to view it enlarged",
    modalWidth: "Modal width",
    modalWidthDesc: "Width of the zoom modal (percentage of viewport)",
    modalHeight: "Modal height",
    modalHeightDesc: "Height of the zoom modal (percentage of viewport)",
    customCss: "Custom CSS",
    customCssDesc: "CSS to inject into Obsidian (applies immediately)",
    customCssPlaceholder: "/* Enter your custom CSS here */",
    reset: "Reset to default",
    downloadPng: "Download PNG",
    zoom: "Zoom",
    converting: "Converting...",
    defaultZoomLevel: "Default zoom level",
    defaultZoomLevelDesc: "Initial zoom level when opening a Mermaid diagram (percentage)",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fitView: "Fit",
    savePng: "Save PNG",
    savedToVault: "Saved to vault: ",
    pngSaveFailed: "Failed to save PNG",
    enhanceReadability: "Enhance diagram readability",
    enhanceReadabilityDesc: "Thicken connector lines and, in dark mode, brighten lines and darken subgraph backgrounds. Turn off to match reading view colors exactly"
  },
  zh: {
    settingsTitle: "Better Mermaid \u8BBE\u7F6E",
    languageLabel: "\u8BED\u8A00",
    languageDesc: "\u63D2\u4EF6\u754C\u9762\u7684\u663E\u793A\u8BED\u8A00",
    enableClickToZoom: "\u542F\u7528\u5355\u51FB\u653E\u5927",
    enableClickToZoomDesc: "\u5728\u9605\u8BFB\u6A21\u5F0F\u4E0B\u5355\u51FB Mermaid \u56FE\u8868\u4EE5\u653E\u5927\u67E5\u770B",
    modalWidth: "\u5F39\u7A97\u5BBD\u5EA6",
    modalWidthDesc: "\u5F39\u7A97\u5BBD\u5EA6\uFF08\u89C6\u53E3\u767E\u5206\u6BD4\uFF09",
    modalHeight: "\u5F39\u7A97\u9AD8\u5EA6",
    modalHeightDesc: "\u5F39\u7A97\u9AD8\u5EA6\uFF08\u89C6\u53E3\u767E\u5206\u6BD4\uFF09",
    customCss: "\u81EA\u5B9A\u4E49 CSS",
    customCssDesc: "\u6CE8\u5165\u5230 Obsidian \u7684 CSS\uFF08\u5373\u65F6\u751F\u6548\uFF09",
    customCssPlaceholder: "/* \u5728\u8FD9\u91CC\u8F93\u5165\u81EA\u5B9A\u4E49 CSS */",
    reset: "\u91CD\u7F6E\u4E3A\u9ED8\u8BA4\u503C",
    downloadPng: "\u4E0B\u8F7D PNG",
    zoom: "\u7F29\u653E",
    converting: "\u8F6C\u6362\u4E2D...",
    defaultZoomLevel: "\u9ED8\u8BA4\u7F29\u653E\u7EA7\u522B",
    defaultZoomLevelDesc: "\u6253\u5F00 Mermaid \u56FE\u8868\u65F6\u7684\u521D\u59CB\u7F29\u653E\u7EA7\u522B\uFF08\u767E\u5206\u6BD4\uFF09",
    zoomIn: "\u653E\u5927",
    zoomOut: "\u7F29\u5C0F",
    fitView: "\u9002\u5E94",
    savePng: "\u4FDD\u5B58 PNG",
    savedToVault: "\u5DF2\u4FDD\u5B58\u5230\u4ED3\u5E93: ",
    pngSaveFailed: "PNG \u4FDD\u5B58\u5931\u8D25",
    enhanceReadability: "\u589E\u5F3A\u56FE\u8868\u53EF\u8BFB\u6027",
    enhanceReadabilityDesc: "\u52A0\u7C97\u8FDE\u7EBF\uFF0C\u5E76\u5728\u6DF1\u8272\u6A21\u5F0F\u4E0B\u63D0\u4EAE\u8FDE\u7EBF\u3001\u6697\u8272\u5316 subgraph \u533A\u5757\u3002\u5173\u95ED\u540E\u5F39\u7A97\u914D\u8272\u4E0E\u9605\u8BFB\u89C6\u56FE\u5B8C\u5168\u4E00\u81F4"
  }
};
function i18n(lang, key) {
  var _a, _b;
  const dict = (_a = STRINGS[lang]) != null ? _a : STRINGS["en"];
  return (_b = dict[key]) != null ? _b : key;
}
var BetterMermaidSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  t(key) {
    return i18n(this.plugin.settings.language, key);
  }
  /**
   * Declarative settings (Obsidian 1.13+): the definitions are rendered by
   * Obsidian and indexed into the settings search.  This requires
   * minAppVersion 1.13.0; older runtimes are no longer supported.
   */
  getSettingDefinitions() {
    const reset = (key) => ({
      name: this.t("reset"),
      action: () => {
        const settings = this.plugin.settings;
        const defaults = DEFAULT_SETTINGS;
        settings[key] = defaults[key];
        void this.plugin.saveSettings();
        this.update();
      }
    });
    return [
      {
        type: "group",
        heading: this.t("settingsTitle"),
        items: [
          {
            name: this.t("languageLabel"),
            desc: this.t("languageDesc"),
            control: {
              type: "dropdown",
              key: "language",
              options: { en: "English", zh: "\u4E2D\u6587" }
            }
          },
          {
            name: this.t("enableClickToZoom"),
            desc: this.t("enableClickToZoomDesc"),
            control: { type: "toggle", key: "enableClickToZoom" }
          },
          {
            name: this.t("enhanceReadability"),
            desc: this.t("enhanceReadabilityDesc"),
            control: { type: "toggle", key: "enhanceReadability" }
          },
          {
            name: this.t("modalWidth"),
            desc: this.t("modalWidthDesc"),
            control: {
              type: "slider",
              key: "modalWidthPercent",
              min: 30,
              max: 100,
              step: 5,
              displayFormat: (value) => `${value}%`
            }
          },
          reset("modalWidthPercent"),
          {
            name: this.t("modalHeight"),
            desc: this.t("modalHeightDesc"),
            control: {
              type: "slider",
              key: "modalHeightPercent",
              min: 30,
              max: 100,
              step: 5,
              displayFormat: (value) => `${value}%`
            }
          },
          reset("modalHeightPercent"),
          {
            name: this.t("defaultZoomLevel"),
            desc: this.t("defaultZoomLevelDesc"),
            control: {
              type: "slider",
              key: "defaultZoomLevel",
              min: 20,
              max: 200,
              step: 5,
              displayFormat: (value) => `${value}%`
            }
          },
          reset("defaultZoomLevel"),
          {
            name: this.t("customCss"),
            desc: this.t("customCssDesc"),
            control: {
              type: "textarea",
              key: "customCss",
              rows: 8,
              placeholder: this.t("customCssPlaceholder")
            }
          }
        ]
      }
    ];
  }
  getControlValue(key) {
    const settings = this.plugin.settings;
    return settings[key];
  }
  async setControlValue(key, value) {
    const settings = this.plugin.settings;
    settings[key] = value;
    await this.plugin.saveSettings();
    if (key === "language") {
      this.update();
    }
  }
};

// src/modal.ts
var import_obsidian2 = require("obsidian");
var ZOOM_OPTIONS = [
  { label: "20%", value: 0.2 },
  { label: "50%", value: 0.5 },
  { label: "75%", value: 0.75 },
  { label: "100%", value: 1 }
];
var MIN_SCALE = 0.1;
var MAX_SCALE = 10;
var ZOOM_STEP = 1.5;
var DOUBLE_TAP_MS = 300;
var TAP_MOVE_TOLERANCE = 12;
var MermaidImageModal = class extends import_obsidian2.Modal {
  constructor(app, svg, settings) {
    super(app);
    this.scale = 1;
    this.panX = 0;
    this.panY = 0;
    this.isDragging = false;
    this.dragMoved = false;
    this.dragStartX = 0;
    this.dragStartY = 0;
    this.panStartX = 0;
    this.panStartY = 0;
    this.resizeObserver = null;
    // Active touch/pen/mouse pointers (coordinates relative to the viewport).
    this.pointers = /* @__PURE__ */ new Map();
    this.pinchStartDist = 0;
    this.pinchStartScale = 1;
    this.lastTapTime = 0;
    this.lastTapX = 0;
    this.lastTapY = 0;
    this.onWheel = (e) => {
      e.preventDefault();
      if (e.shiftKey && !e.ctrlKey) {
        this.panX -= e.deltaY;
        this.updateTransform();
        return;
      }
      const rect = this.viewport.getBoundingClientRect();
      const mx = e.clientX - rect.left - rect.width / 2;
      const my = e.clientY - rect.top - rect.height / 2;
      const factor = 1 - e.deltaY * 5e-3;
      const newScale = this.clampScale(this.scale * factor);
      const ratio = newScale / this.scale;
      this.panX = mx + (this.panX - mx) * ratio;
      this.panY = my + (this.panY - my) * ratio;
      this.scale = newScale;
      this.applyView();
      this.syncZoomDisplay(newScale);
    };
    this.onPointerDown = (e) => {
      if (e.pointerType === "mouse" && e.button !== 0)
        return;
      const target = e.target;
      if (target.closest(".better-mermaid-controls"))
        return;
      const pos = this.pointerPos(e);
      this.pointers.set(e.pointerId, pos);
      try {
        this.viewport.setPointerCapture(e.pointerId);
      } catch (e2) {
      }
      if (this.pointers.size === 1) {
        this.isDragging = true;
        this.dragMoved = false;
        this.dragStartX = pos.x;
        this.dragStartY = pos.y;
        this.panStartX = this.panX;
        this.panStartY = this.panY;
        this.viewport.addClass("better-mermaid-grabbing");
      } else if (this.pointers.size === 2) {
        this.pinchStartDist = this.pointerDistance();
        this.pinchStartScale = this.scale;
      }
    };
    this.onPointerMove = (e) => {
      if (!this.pointers.has(e.pointerId))
        return;
      const pos = this.pointerPos(e);
      this.pointers.set(e.pointerId, pos);
      if (this.pointers.size >= 2 && this.pinchStartDist > 0) {
        const dist = this.pointerDistance();
        if (dist <= 0)
          return;
        this.dragMoved = true;
        const newScale = this.clampScale(
          this.pinchStartScale * (dist / this.pinchStartDist)
        );
        const rect = this.viewport.getBoundingClientRect();
        const mid = this.pointerMidpoint();
        const mx = mid.x - rect.width / 2;
        const my = mid.y - rect.height / 2;
        const ratio = newScale / this.scale;
        this.panX = mx + (this.panX - mx) * ratio;
        this.panY = my + (this.panY - my) * ratio;
        this.scale = newScale;
        this.applyView();
        this.syncZoomDisplay(newScale);
      } else if (this.pointers.size === 1 && this.isDragging) {
        if (Math.hypot(pos.x - this.dragStartX, pos.y - this.dragStartY) > TAP_MOVE_TOLERANCE) {
          this.dragMoved = true;
        }
        if (e.cancelable)
          e.preventDefault();
        this.panX = this.panStartX + (pos.x - this.dragStartX);
        this.panY = this.panStartY + (pos.y - this.dragStartY);
        this.updateTransform();
      }
    };
    this.onPointerUp = (e) => {
      const tracked = this.pointers.delete(e.pointerId);
      const upTarget = e.target;
      const inControls = !!upTarget.closest(".better-mermaid-controls");
      if (this.pointers.size === 0) {
        const wasPinching = this.pinchStartDist > 0;
        this.isDragging = false;
        this.pinchStartDist = 0;
        this.viewport.removeClass("better-mermaid-grabbing");
        if (tracked && !wasPinching && !this.dragMoved && !inControls) {
          this.handleTap(e);
        }
        this.dragMoved = false;
      } else if (this.pointers.size === 1) {
        this.pinchStartDist = 0;
        this.isDragging = true;
        const rest = Array.from(this.pointers.values())[0];
        this.dragStartX = rest.x;
        this.dragStartY = rest.y;
        this.panStartX = this.panX;
        this.panStartY = this.panY;
      }
    };
    this.onPointerCancel = (e) => {
      this.pointers.delete(e.pointerId);
      this.isDragging = false;
      this.pinchStartDist = 0;
      this.dragMoved = false;
      this.viewport.removeClass("better-mermaid-grabbing");
    };
    this.svg = svg;
    this.settings = settings;
    this.scale = settings.defaultZoomLevel / 100;
    this.modalEl.addClass("better-mermaid-modal-size");
  }
  t(key) {
    return i18n(this.settings.language, key);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("better-mermaid-modal");
    this.svgEl = this.svg.cloneNode(true);
    this.svgEl.removeAttribute("width");
    this.svgEl.removeAttribute("height");
    this.svgEl.removeAttribute("style");
    this.svgEl.setAttribute("preserveAspectRatio", "xMidYMid meet");
    this.svgEl.addClass("better-mermaid-svg");
    this.viewport = contentEl.createDiv({ cls: "better-mermaid-viewport" });
    this.viewport.appendChild(this.svgEl);
    window.requestAnimationFrame(() => {
      this.applyView();
    });
    this.resizeObserver = new ResizeObserver(() => {
      this.applyView();
    });
    this.resizeObserver.observe(this.viewport);
    const controls = contentEl.createDiv({ cls: "better-mermaid-controls" });
    controls.createEl("label", { text: this.t("zoom") });
    this.zoomSelect = controls.createEl("select");
    ZOOM_OPTIONS.forEach((opt) => {
      const option = this.zoomSelect.createEl("option");
      option.value = String(opt.value);
      option.text = opt.label;
    });
    this.zoomSelect.value = String(this.scale);
    this.zoomSelect.addEventListener("change", () => {
      const gen = this.zoomSelect.querySelector("[data-generated]");
      if (gen)
        gen.remove();
      this.setZoom(parseFloat(this.zoomSelect.value));
    });
    this.addZoomButton(
      controls,
      "\u2212",
      "zoomOut",
      () => this.zoomBy(1 / ZOOM_STEP)
    );
    this.addZoomButton(controls, "+", "zoomIn", () => this.zoomBy(ZOOM_STEP));
    const fitBtn = controls.createEl("button", { text: this.t("fitView") });
    fitBtn.addEventListener("click", () => this.resetView());
    const btn = controls.createEl("button", {
      text: import_obsidian2.Platform.isMobile ? this.t("savePng") : this.t("downloadPng")
    });
    btn.addEventListener("click", () => {
      void this.handleDownload(btn);
    });
    this.viewport.addEventListener("wheel", this.onWheel, { passive: false });
    this.viewport.addEventListener("pointerdown", this.onPointerDown);
    this.viewport.addEventListener("pointermove", this.onPointerMove);
    this.viewport.addEventListener("pointerup", this.onPointerUp);
    this.viewport.addEventListener("pointercancel", this.onPointerCancel);
  }
  onClose() {
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
    this.viewport.removeEventListener("wheel", this.onWheel);
    this.viewport.removeEventListener("pointerdown", this.onPointerDown);
    this.viewport.removeEventListener("pointermove", this.onPointerMove);
    this.viewport.removeEventListener("pointerup", this.onPointerUp);
    this.viewport.removeEventListener("pointercancel", this.onPointerCancel);
    this.pointers.clear();
    this.pinchStartDist = 0;
    this.contentEl.empty();
    this.scale = 1;
    this.panX = 0;
    this.panY = 0;
    this.isDragging = false;
    this.dragMoved = false;
  }
  addZoomButton(parent, text, ariaKey, onClick) {
    const button = parent.createEl("button", { text });
    button.setAttribute("aria-label", this.t(ariaKey));
    button.addEventListener("click", onClick);
  }
  zoomBy(factor) {
    this.setZoom(this.clampScale(this.scale * factor));
  }
  resetView() {
    this.panX = 0;
    this.panY = 0;
    this.scale = 1;
    this.applyView();
    this.syncZoomDisplay(1);
  }
  clampScale(scale) {
    return Math.max(MIN_SCALE, Math.min(MAX_SCALE, scale));
  }
  setZoom(scale) {
    const ratio = scale / this.scale;
    this.panX *= ratio;
    this.panY *= ratio;
    this.scale = scale;
    this.applyView();
    this.syncZoomDisplay(scale);
  }
  syncZoomDisplay(scale) {
    const gen = this.zoomSelect.querySelector("[data-generated]");
    if (gen)
      gen.remove();
    const exact = ZOOM_OPTIONS.find((o) => Math.abs(o.value - scale) < 5e-3);
    if (exact) {
      this.zoomSelect.value = String(exact.value);
      return;
    }
    const doc = this.contentEl.ownerDocument;
    const opt = doc.createElement("option");
    opt.setAttribute("data-generated", "true");
    opt.value = String(scale);
    opt.text = `${Math.round(scale * 100)}%`;
    this.zoomSelect.appendChild(opt);
    this.zoomSelect.value = String(scale);
  }
  /**
   * Toggle between the fitted view (scale 1) and 2x zoom on a quick tap
   * without significant movement.  Works for both touch and mouse
   * (double-click).
   */
  handleTap(e) {
    const now = Date.now();
    const dx = e.clientX - this.lastTapX;
    const dy = e.clientY - this.lastTapY;
    const isDoubleTap = now - this.lastTapTime < DOUBLE_TAP_MS && Math.hypot(dx, dy) < TAP_MOVE_TOLERANCE;
    if (isDoubleTap) {
      if (this.scale > 1.01) {
        this.panX = 0;
        this.panY = 0;
        this.scale = 1;
      } else {
        const pos = this.pointerPos(e);
        const rect = this.viewport.getBoundingClientRect();
        const mx = pos.x - rect.width / 2;
        const my = pos.y - rect.height / 2;
        const target = 2;
        const ratio = target / this.scale;
        this.panX = mx + (this.panX - mx) * ratio;
        this.panY = my + (this.panY - my) * ratio;
        this.scale = target;
      }
      this.applyView();
      this.syncZoomDisplay(this.scale);
      this.lastTapTime = 0;
    } else {
      this.lastTapTime = now;
      this.lastTapX = e.clientX;
      this.lastTapY = e.clientY;
    }
  }
  pointerPos(e) {
    const rect = this.viewport.getBoundingClientRect();
    return { x: e.clientX - rect.left, y: e.clientY - rect.top };
  }
  pointerDistance() {
    const pts = Array.from(this.pointers.values());
    if (pts.length < 2)
      return 0;
    return Math.hypot(pts[0].x - pts[1].x, pts[0].y - pts[1].y);
  }
  pointerMidpoint() {
    const pts = Array.from(this.pointers.values());
    return {
      x: (pts[0].x + pts[1].x) / 2,
      y: (pts[0].y + pts[1].y) / 2
    };
  }
  /**
   * Reposition the SVG (translate only — never CSS scale).  Scaling is done
   * by changing the SVG's pixel size in applyView(), so the browser
   * re-renders the vector content at the exact target size instead of
   * upscaling a raster texture (which would blur text and strokes).
   */
  updateTransform() {
    this.svgEl.style.transform = `translate(${this.panX}px, ${this.panY}px)`;
  }
  /**
   * Size the SVG to the viewport-fit dimensions (derived from the viewBox
   * attribute, aspect ratio preserved) multiplied by the current zoom level.
   * The viewport flex-centers the SVG (see styles.css); pan offsets from
   * updateTransform() are applied on top of that centering.
   */
  applyView() {
    const viewBox = this.svgEl.getAttribute("viewBox");
    if (!viewBox)
      return;
    const parts = viewBox.split(/\s+/).map(Number);
    if (parts.length !== 4)
      return;
    const vbWidth = parts[2];
    const vbHeight = parts[3];
    if (!vbWidth || !vbHeight)
      return;
    const vpRect = this.viewport.getBoundingClientRect();
    const vpWidth = vpRect.width;
    const vpHeight = vpRect.height;
    if (!vpWidth || !vpHeight)
      return;
    const svgAspect = vbWidth / vbHeight;
    const vpAspect = vpWidth / vpHeight;
    let fitWidth;
    let fitHeight;
    if (svgAspect > vpAspect) {
      fitWidth = vpWidth;
      fitHeight = vpWidth / svgAspect;
    } else {
      fitHeight = vpHeight;
      fitWidth = vpHeight * svgAspect;
    }
    this.svgEl.style.width = `${fitWidth * this.scale}px`;
    this.svgEl.style.height = `${fitHeight * this.scale}px`;
    this.updateTransform();
  }
  async handleDownload(btn) {
    const originalText = import_obsidian2.Platform.isMobile ? this.t("savePng") : this.t("downloadPng");
    btn.setText(this.t("converting"));
    btn.disabled = true;
    try {
      const pngDataUrl = await this.svgToPng();
      if (import_obsidian2.Platform.isMobile) {
        await this.savePngOnMobile(pngDataUrl);
      } else {
        const doc = this.contentEl.ownerDocument;
        const link = doc.createElement("a");
        link.download = "mermaid-diagram.png";
        link.href = pngDataUrl;
        link.click();
      }
    } catch (e) {
      console.error("Failed to convert SVG to PNG:", e);
      new import_obsidian2.Notice(this.t("pngSaveFailed"));
    }
    btn.setText(originalText);
    btn.disabled = false;
  }
  /**
   * Mobile webviews can't download <a download> data URLs, so try the
   * system share sheet first (save to Files/Photos, send to other apps)
   * and fall back to writing the PNG into the vault when sharing is
   * unavailable or fails.
   */
  async savePngOnMobile(pngDataUrl) {
    const blob = this.dataUrlToBlob(pngDataUrl);
    const fileName = `mermaid-${Date.now()}.png`;
    const file = new File([blob], fileName, { type: "image/png" });
    const shareable = navigator;
    if (shareable.canShare && shareable.share) {
      if (shareable.canShare({ files: [file] })) {
        try {
          await shareable.share({ files: [file], title: fileName });
          return;
        } catch (err) {
          if (err instanceof DOMException && err.name === "AbortError") {
            return;
          }
        }
      }
    }
    const arrayBuffer = await blob.arrayBuffer();
    await this.app.vault.createBinary(fileName, arrayBuffer);
    new import_obsidian2.Notice(`${this.t("savedToVault")}${fileName}`);
  }
  dataUrlToBlob(dataUrl) {
    const comma = dataUrl.indexOf(",");
    const mimeMatch = /^data:([^;]+);/.exec(dataUrl.slice(0, comma));
    const mime = mimeMatch ? mimeMatch[1] : "image/png";
    const binary = atob(dataUrl.slice(comma + 1));
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return new Blob([bytes], { type: mime });
  }
  svgToPng() {
    const cloned = this.svgEl.cloneNode(true);
    cloned.style.removeProperty("transform");
    cloned.style.removeProperty("width");
    cloned.style.removeProperty("height");
    const viewBox = cloned.getAttribute("viewBox");
    if (viewBox) {
      const parts = viewBox.split(/\s+/).map(Number);
      if (parts.length === 4) {
        cloned.setAttribute("width", String(parts[2]));
        cloned.setAttribute("height", String(parts[3]));
      }
    }
    const fixCss = "foreignObject{font-size:13px;line-height:1.35}foreignObject div,foreignObject p,foreignObject span{overflow-wrap:break-word;word-break:break-word;white-space:normal}";
    const styleEl = cloned.ownerDocument.createElementNS(
      "http://www.w3.org/2000/svg",
      "style"
    );
    styleEl.textContent = fixCss;
    cloned.insertBefore(styleEl, cloned.firstChild);
    const serializer = new XMLSerializer();
    const svgString = serializer.serializeToString(cloned);
    const dataUrl = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svgString);
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const doc = this.contentEl.ownerDocument;
        const canvas = doc.createElement("canvas");
        const pxRatio = 2;
        canvas.width = img.width * pxRatio;
        canvas.height = img.height * pxRatio;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          reject(new Error("Failed to get canvas context"));
          return;
        }
        ctx.scale(pxRatio, pxRatio);
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, img.width, img.height);
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      };
      img.onerror = () => {
        reject(new Error("Failed to load SVG image"));
      };
      img.src = dataUrl;
    });
  }
};

// src/main.ts
var BetterMermaidPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.cssSheet = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BetterMermaidSettingTab(this.app, this));
    this.injectCSS();
    this.registerDomEvent(
      this.app.workspace.containerEl,
      "click",
      (evt) => {
        if (!this.settings.enableClickToZoom)
          return;
        const target = evt.target;
        const mermaidContainer = target.closest("div.mermaid");
        if (!mermaidContainer)
          return;
        const mermaidSvg = mermaidContainer.querySelector("svg");
        if (!mermaidSvg)
          return;
        new MermaidImageModal(
          this.app,
          mermaidSvg,
          this.settings
        ).open();
      },
      true
    );
  }
  onunload() {
    this.removeCSS();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.injectCSS();
  }
  injectCSS() {
    this.removeCSS();
    const sizing = `
.better-mermaid-modal-size {
  width: ${this.settings.modalWidthPercent}vw;
  max-width: ${this.settings.modalWidthPercent}vw;
  height: ${this.settings.modalHeightPercent}vh;
  max-height: ${this.settings.modalHeightPercent}vh;
}`;
    const readability = this.settings.enhanceReadability ? `
.better-mermaid-viewport path,
.better-mermaid-viewport line,
.better-mermaid-viewport polyline {
  stroke-width: 2.5px !important;
}
.theme-dark .better-mermaid-viewport path,
.theme-dark .better-mermaid-viewport line,
.theme-dark .better-mermaid-viewport polyline {
  stroke: var(--text-normal) !important;
}
/* Direct-child selectors keep node rects inside clusters untouched. */
.theme-dark .better-mermaid-viewport g.cluster > rect,
.theme-dark .better-mermaid-viewport g.cluster > polygon {
  fill: rgba(255, 255, 255, 0.05) !important;
  stroke: var(--text-muted) !important;
}
.theme-dark .better-mermaid-viewport g.cluster .cluster-label text {
  fill: var(--text-normal) !important;
}
.theme-dark .better-mermaid-viewport g.cluster .cluster-label div,
.theme-dark .better-mermaid-viewport g.cluster .cluster-label span {
  color: var(--text-normal) !important;
}` : "";
    const allCss = sizing + "\n" + readability + "\n" + (this.settings.customCss || "");
    if (!allCss.trim())
      return;
    try {
      this.cssSheet = new CSSStyleSheet();
      this.cssSheet.replaceSync(allCss);
      const doc = this.app.workspace.containerEl.ownerDocument;
      doc.adoptedStyleSheets = [
        ...doc.adoptedStyleSheets,
        this.cssSheet
      ];
    } catch (e) {
    }
  }
  removeCSS() {
    if (this.cssSheet) {
      const doc = this.app.workspace.containerEl.ownerDocument;
      doc.adoptedStyleSheets = Array.from(
        doc.adoptedStyleSheets
      ).filter((s) => s !== this.cssSheet);
      this.cssSheet = null;
    }
  }
};
